### ISSUE TITLE
During the login process, focused fields aren't obvious/noticeable

### ISSUE THREAD

**Issue by maxwelljordanwhite** [vasanthv/producthunt-desktop#1]

**Comment by vasanthv** [comment]
@maxwelljordanwhite can you share a screenshot?

**Comment by maxwelljordanwhite** [comment]
@vasanthv Sure thing, here's a quick video: https://d.pr/v/AZeZc2

I am clicking the inputs (but couldn't capture my clicks). I hope this helps. Cool app!
